### PR TITLE
known-issues: Update

### PR DESCRIPTION
**Pull request by smcv**
(see individual commits, there are many)

### CODE REVIEW

**Comment by smcv** [comment]
Now that we've shipped the "slim" version of scout as the default, this needs more updates.

**Comment by TTimo** [comment]
There is no scout_layered_slim beta branch anymore. I cleaned that one out with the promotion of the various betas to stable on 7/19

**Comment by smcv** [comment]
> Now that we've shipped the "slim" version of scout as the default, this needs more updates.

Mostly updated for the new scout runtime now. I haven't tried Haxe/Hashlink games yet.

I now have access to Evoland Legendary Edition, so I'll try that at some point.

I think we discussed Dead Cells elsewhere and the conclusion was that the new runtime was necessary but not sufficient, so that one will stay as "probably not working" until we can pile on some more workarounds.

**Comment by smcv** [comment]
I've updated the known issues document again, generalizing the section about Haxe/Hashlink games to refer more generally to games that reset the `LD_LIBRARY_PATH`. Game Dev Tycoon (#198) is an example of a non-Haxe game in this category.

**Pull request merged**
